services:
  web:
    build: .
    ports:
      - 5000:5000
    env_file: .env
    environment:
      - MONGODB_URL=mongodb://mongo:27017/authServer
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./:/usr/AuthServer
    command: npm run start

  mongo:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/dbconfig

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - '6379:6379'

volumes:
  mongodb:
  mongodb_config:
