services:
    web:
        build: .
        ports: 
            - 5000:5000
        env_file: .env
        environment: 
            - MONGODB_URL=mongodb://mongo:27017/authServer
        volumes: 
            - ./:/usr/AuthServer
        networks:
            - mongo
        command: npm run start
    
    mongo:
        image: mongo:4.4.3
        ports: 
            - 27017:27017
        volumes: 
            - mongodb:/data/db
            - mongodb_config:/data/dbconfig
        networks:
            - mongo

networks:
    mongo:

volumes: 
    mongodb:
    mongodb_config: